services:
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - db_staging_data:/var/lib/postgresql/data
  app:
    image: invitation-management:dev
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db_staging_data:
